production:
  adapter: mysql2
  host: <%= ENV['DB_HOST'] %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  database: waker_production
  encoding: utf8mb4

development:
  adapter: mysql2
  database: waker_development
  encoding: utf8mb4

test:
  adapter: mysql2
  database: waker_test
  encoding: utf8mb4
